apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-credentials-template-jd-org1
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: mgmt-jd-org1-vault-kv-secret
  target:
    name: repo-credentials-template-jd-org1
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          managed-by: argocd.argoproj.io
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      data:
        # Template will be populated from Vault data
        type: "{{ .type }}"
        name: "{{ .name }}"
        url: "{{ .url }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: argocd/repo-credentials-template/jd-org1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-credentials-template-gitops-ing
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: mgmt-jd-org1-vault-kv-secret
  target:
    name: repo-credentials-template-gitops-ing
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          managed-by: argocd.argoproj.io
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      data:
        # Template will be populated from Vault data
        type: "{{ .type }}"
        name: "{{ .name }}"
        url: "{{ .url }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: argocd/repo-credentials-template/jd-org1-platform
