apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-jd-org1-crossplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mgmt-jd-org1
  destination:
    name: mgmt-jd-org1
    namespace: crossplane-system
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: 1.17.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
