apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-jd-org1-cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: mgmt-jd-org1
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.14.4
    helm:
      values: |-
        serviceAccount:
          create: true
          name: cert-manager
          annotations:
            eks.amazonaws.com/role-arn: 'arn:aws:iam::126827061464:role/cert-manager-mgmt-jd-org1'
        installCRDs: true
    chart: cert-manager
  destination:
    name: mgmt-jd-org1
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
