apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-jd-org1-external-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: mgmt-jd-org1
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.19.2
    helm:
      values: |-
        serviceAccount:
          create: true
          name: external-secrets
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::126827061464:role/eso-mgmt-jd-org1
    chart: external-secrets
  destination:
    name: mgmt-jd-org1
    namespace: external-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - ServerSideApplyForce=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
        - .spec.conversion.webhook.clientConfig.service.name
        - .spec.conversion.webhook.clientConfig.service.namespace
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mgmt-jd-org1-eso-kubernetes-external-secrets-auth
  annotations:
    argocd.argoproj.io/sync-wave: '40'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:auth-delegator'
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mgmt-jd-org1-eso-kubernetes-external-secrets-auth2
  annotations:
    argocd.argoproj.io/sync-wave: '40'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'cluster-admin'
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets-operator
