apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::126827061464:role/eso-mgmt-engineering
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-private
  namespace: argocd
spec:
  region: us-east-1
  scope: private
  auth:
    jwt:
      serviceAccountRef:
        name: external-secrets
