apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubefirst
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://charts.konstruct.io
    targetRevision: 2.10.3
    chart: kubefirst-pro
    helm:
      values: |-
        global:
          cloudProvider: "aws"
          clusterId: "9hd3jt"
          clusterType: "mgmt"
          domainName: "gitops.ing"
          gitProvider: "github"
          installMethod: "helm"
          kubefirstClient: "<KUBEFIRST_CLIENT>"
          kubefirstTeam: "false"
          kubefirstTeamInfo: ""
          kubefirstVersion: "v2.10.3"
          useTelemetry: ""
        kubefirst-pro-api:
          extraEnv:
            CLUSTER_NAME: "mgmt-k1-gitops-ing"
          serviceAccount:
            create: true
            annotations: 
              eks.amazonaws.com/role-arn: arn:aws:iam::126827061464:role/kubefirst-pro-api-mgmt-k1-gitops-ing
        kubefirst-pro-ui:
          domain: "gitops.ing"
          extraEnvSecrets:
            CLIENT_ID:
              name: kubefirst-console-secrets
              key: client_id
            SECRET_ID:
              name: kubefirst-console-secrets
              key: client_secret
          ingress:
            enabled: "true"
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              
              
              
            hosts:
              - host: kubefirst.gitops.ing
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: kubefirst-tls
                hosts:
                  - kubefirst.gitops.ing
  destination:
    name: in-cluster
    namespace: kubefirst
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
