apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: crossplane-secrets
  namespace: crossplane-system
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: /crossplane
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: mgmt-jd-org1-vault-kv-secret
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: crossplane-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  target:
    name: git-credentials
    template:
      engineVersion: v2
      data:
        creds: |
          https://{{ .username }}:{{ .password }}@github.com
  secretStoreRef:
    kind: ClusterSecretStore
    name: mgmt-jd-org1-vault-kv-secret
  refreshInterval: 10s
  data:
    - remoteRef:
        key: argocd/repo-credentials-template/jd-org1
        property: username
        conversionStrategy: Default
      secretKey: username
    - remoteRef:
        key: argocd/repo-credentials-template/jd-org1
        property: password
        conversionStrategy: Default
      secretKey: password
