apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-config
  namespace: dex
spec:
  target:
    name: dex-config
    template:
      type: Opaque
      engineVersion: v2
      data:
        config.yaml: |
          issuer: https://dex.gitops.ing
          logger:
            level: "info"
            format: "json"
          storage:
            type: kubernetes
            config:
              inCluster: true
          web:
            http: 0.0.0.0:5556
            skipApprovalScreen: true
            allowedOrigins:
              - "http://localhost:5555"
              - "http://127.0.0.1:5555"
              - "https://konstruct.gitops.ing"
          grpc:
            addr: 0.0.0.0:5557
          telemetry:
            http: 0.0.0.0:5558
          oauth2:
            skipApprovalScreen: true
          enablePasswordDB: true
          staticPasswords:
          - email: "admin@example.com"
            hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"  # password: "password"
            username: "admin"
            userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
            groups:
              - "admin"
              - "konstruct-users"
            displayName: "Admin User"
            givenName: "Admin"
            familyName: "User"
          connectors:
            - config:
                clientID: {{ .AZURE_CLIENT_ID }}
                clientSecret: {{ .AZURE_CLIENT_SECRET }}
                tenant: {{ .AZURE_TENANT_ID }}
                loadAllGroups: true
                redirectURI: https://dex.gitops.ing/callback
                scopes:
                - openid
                - profile
                - email
              id: azure
              name: Azure AD
              type: microsoft
          staticClients:
          {{- $clients := .STATIC_CLIENTS_JSON | fromJson }}
          {{- range $clients }}
            - id: {{ .id }}
              name: {{ .name }}
              redirectURIs:
              {{- range .redirectURIs }}
                - {{ . }}
              {{- end }}
              secret: {{ .secret }}
              public: {{ .public }}
          {{- end }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  data:
  - secretKey: STATIC_CLIENTS_JSON
    remoteRef:
      key: /konstruct/dex
      property: STATIC_CLIENTS_JSON
  - secretKey: AZURE_CLIENT_ID
    remoteRef:
      key: /konstruct/dex
      property: AZURE_CLIENT_ID
  - secretKey: AZURE_CLIENT_SECRET
    remoteRef:
      key: /konstruct/dex
      property: AZURE_CLIENT_SECRET
  - secretKey: AZURE_TENANT_ID
    remoteRef:
      key: /konstruct/dex
      property: AZURE_TENANT_ID
