apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cwfts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: default
  source:
    repoURL: https://github.com/gitops-ing/gitops.git
    path: registry/clusters/mgmt-k1-gitops-ing/components/argo-workflows/cwfts
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
